### ISSUE TITLE
Support at least 8.2

### ISSUE THREAD

**Issue by dungi** [PiXeL16/RevealingSplashView#1]
Hello,

i like your framework. Great work.
But I like to support my App for iOS 8.0 and above. But this Frameworks just wanted iOS 9.2 as oldest Software. Can you fix this? Thank you.

**Comment by PiXeL16** [comment]
Hi,
I updated the Deployment Target to 8.0. And an update version of the Pod #0.0.2 has been submitted. Please run `pod update` test and let me know.
Thanks

**Comment by dungi** [comment]
Okay :+1: 
Its Working Fine - Thank you

PS: I used Carthage. Because I don't like to use Cocoapods. But it has to work for both.

**Comment by PiXeL16** [comment]
Cool! Nice to hear that. A `PR` for Carthage support would be very welcome :wink:

**Comment by dungi** [comment]
I just add "github "PiXeL16/RevealingSplashView" to my Cartfile
