### ISSUE TITLE
Issues after pod install

### ISSUE THREAD

**Issue by ekdysis** [PiXeL16/RevealingSplashView#10]
Upon installing the **RevealingSplashView** cocoa pod in my project, I end up with a ton of errors that don't really enable me to use the pod at all. I followed the installation guide and even tried to migrate some of the code to Swift 2.3 (as I wasn't sure if maybe the files were outdated or not) but there seems to be a minor issue when trying to install the pod version 0.0.9.

**Comment by PiXeL16** [comment]
Hey @SwiftisLife Not sure what you mean with migrating the code to Swift 2.3. The Library is currently updated to work with Swift 3.0. If you need 2.3 you will need to use Release 0.0.5.
Also, how are you installing the library? CocoaPods?

**Comment by ekdysis** [comment]
Yeah, I installed it using CocoaPods. And apologies on the confusion, thanks for clarifying my issue.

 Looks like I'll be using 0.0.5 for my project.

**Comment by PiXeL16** [comment]
No worries, Let me know how it goes. 👍 . Closing for now, let me know if you run into any other issues.

**Comment by SwiftisLife** [comment]
Oh yeah, do you have the documentation for 0.5 available?
