### ISSUE TITLE
Use default icon color?

### ISSUE THREAD

**Issue by ekdysis** [PiXeL16/RevealingSplashView#12]
I read through the documentation for **RevealingSplashView**, I was wondering if there's a way to use the default icon color instead of using a custom icon color?

**Comment by PiXeL16** [comment]
Hey @SwiftisLife That was fixed on the latest version, Since you are using 0.0.5 I dont think thats in yet. Can you try 0.0.6, I think that was about the time that that was fixed and still on Swift 2.3.
Let me know!

**Comment by ekdysis** [comment]
@PiXeL16 Are you able to provide documentation to accomplish desired outcome before I upgrade from  **0.0.5** to **0.0.6**?

**Comment by PiXeL16** [comment]
There is no fix for that on `0.0.5` besides changing the Pods code.  If you want to modify the code, you can take a look at this [commit](https://github.com/PiXeL16/RevealingSplashView/commit/4f2959c18eea69535224958fffefb5ef74e2885c) .
But again I will recommend that you use 0.0.6 if you still on `Swift 2.3`
