### ISSUE TITLE
Carthage and swift 3

### ISSUE THREAD

**Issue by andresilvagomez** [PiXeL16/RevealingSplashView#15]
The following build commands failed:
    PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/andresilvagomez/Library/Developer/Xcode/DerivedData/RevealingSplashView-gdkhobhohlmxddbnbzxirdhzohme/Build/Intermediates/RevealingSplashView.build/Release-iphoneos/RevealingSplashView.build/Script-E79891EEF61AFCD36E51FC4B.sh
(1 failure)
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/andresilvagomez/CityTaxi/iOS/Carthage/Checkouts/RevealingSplashView/RevealingSplashView.xcworkspace -scheme RevealingSplashView -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/andresilvagomez/Library/Developer/Xcode/DerivedData/RevealingSplashView-gdkhobhohlmxddbnbzxirdhzohme/Build/Intermediates/RevealingSplashView.build/Release-iphoneos/RevealingSplashView.build/Script-E79891EEF61AFCD36E51FC4B.sh

**Comment by PiXeL16** [comment]
Hi Andre,
I dont really use Carthage, It was working in other version prior to Swift 3.0.
Any idea what could be the problem. Looks like its using CocoaPods even when you are installing with Carthage?

**Comment by andresilvagomez** [comment]
@PiXeL16 I gonna be work on that and I send a pull request with Carthage support 👍

**Comment by PiXeL16** [comment]
Nice 👍 🎉

**Comment by PiXeL16** [comment]
Hey @andresilvagomez I just pushed some Pod changes to `master` that may fix your issue with `Carthage`, please give it a try again and let me know if it works.
Thanks!

**Comment by PiXeL16** [comment]
Closing for now, please re-open if you have any more issues.
