### ISSUE TITLE
Unable to install (pod)

### ISSUE THREAD

**Issue by saldous** [PiXeL16/RevealingSplashView#16]
I've tried, rebooted, re-installed CocoaPods etc. Just can't get it to install !

Terminal gives the error:
Analyzing dependencies
[!] Unable to find a specification for `RevealingSplashView`

any ideas?

**Comment by PiXeL16** [comment]
Hey @saldous, thats weird? 
Nothing pops up in my mind with that error message. Do you have an stable internet connection?, what version of CocoaPods are you using?

**Comment by tonymuu** [comment]
I don't know if this will help - but try pod update?

Also can you show a snippet of your podfile?

**Comment by PiXeL16** [comment]
Closing due to lack of response, please re-open if you have more issues 👍
