### ISSUE TITLE
Is there a possibility to add a label or imageview to the view?

### ISSUE THREAD

**Issue by nalogowiec** [PiXeL16/RevealingSplashView#19]
guys, just a quick question - is there a possibility of adding either a label or another image view above the one that expands? For example - there would be a name twitter and below it - in the screen center - would be the icon that expands (and label stays untouched and disappears...). How can I achieve this effect?

**Comment by PiXeL16** [comment]
Hey @nalogowiec, currently that is not supported. But a `PR` is always welcome 😉.
Have you try making your label or text part of your splash image? Or do you also need to localize that text?

**Comment by nalogowiec** [comment]
Hm, I thought about localizing the text, so putting it as an image view is not an option for me... Also, I thought it would be cool that the text stays untouched when the icon grows up :) I'm not sure whether it's possible, it was just a thought at this point :) anyway - the way it works so far - it's really awesome, easy to configure, great work man!

**Comment by PiXeL16** [comment]
👍 Closing for now!
