### ISSUE TITLE
Add the animation to Appdelegate

### ISSUE THREAD

**Issue by mshll** [PiXeL16/RevealingSplashView#2]
Hello,
I tried to add this to app delegate didFinishLaunchingWithOptions
but it's not working... you know any idea to make it work?

**Comment by PiXeL16** [comment]
Hi,
Any particular reason that you want to put this on your `delegate`?
Ideally the component was designed so you put it in your entry point `ViewController`, in the `viewDidLoad()` method.

Per the documentation:

```
import RevealingSplashView

override func viewDidLoad() {
        super.viewDidLoad()

        //Initialize a revealing Splash with with the iconImage, the initial size and the background color
        let revealingSplashView = RevealingSplashView(iconImage: UIImage(named: "twitterLogo")!,iconInitialSize: CGSizeMake(70, 70), backgroundColor: UIColor(rgba:"#1D8FF1"))

        //Adds the revealing splash view as a sub view
        self.view.addSubview(revealingSplashView)

        //Starts animation
        revealingSplashView.startAnimation(){
            print("Completed")
        }

    }
```

**Comment by PiXeL16** [comment]
Closing the issue for now because of the lack of response. Let me know if you have any more problems :smile:
