### ISSUE TITLE
[HOW] to animate in waiting something

### ISSUE THREAD

**Issue by gorbat-o** [PiXeL16/RevealingSplashView#21]
Hi, 

How to animate until something like an API callback success ?
i cant play with daily because i don't know how many times taking the API call :/

thanks

**Comment by PiXeL16** [comment]
Hi @gorbat-o 
The only animation that support this at the moment is the `HeartBeat` animation. You can play normally and then just call. `finishHeartBeatAnimation` after your API callback success.
A `PR` is welcome to at this functionality to the rest of the animation 😉

**Comment by gorbat-o** [comment]
hey, 

thanks to that, it's exactly what i want,
maybe one day i'm gonna PR ;)

see ya

**Comment by PiXeL16** [comment]
You can also set the `heartAttack` property to true to make it stop.
👍
