### ISSUE TITLE
when I display splashView on the first screen of the app - works fine, otherwise it doesn't

### ISSUE THREAD

**Issue by nalogowiec** [PiXeL16/RevealingSplashView#22]
First of all - great plugin, I love it! I'm using .twitter animation type and in my code when I set the StoryBoard Entry Point to the view with splashView (that is set up in viewDidLoad()) - it works great, I see my logo that shrinks and then expands. 

But when I put this code in some other view that is reachable by normal segue (push type, animated: false for this segue) - then the icon doesn't shrink - it just immediately expands. Does anyone had a similar problem?

**Comment by PiXeL16** [comment]
Hey, I really have not use `RevealingSplashView` for that purpose. Did you found a solution?
Maybe, just using a normal animation in those cases should do the trick no?

**Comment by PiXeL16** [comment]
Closing due to lack of response. Please re-open if you have any more information.
