### ISSUE TITLE
supportedInterfaceOrientations not supported

### ISSUE THREAD

**Issue by ghost** [PiXeL16/RevealingSplashView#23]
Hi,

RevealingSplashView has some problems if you try to rotate the screen when launching. No one know how to fix it please?

Thanks

**Comment by PiXeL16** [comment]
Hello,
What sort of problems are you experience when rotating the screen?

**Comment by ghost** [comment]
This was my problem: [http://i.imgur.com/dGjj0N2.png](http://i.imgur.com/dGjj0N2.png)

Patched with: 


    var loaded = false
    override var shouldAutorotate: Bool {
        return loaded
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        revealingSplashView.startAnimation() {
            DispatchQueue.main.async {
                self.loaded = true
            }
        }
    }


Maybe add this snippet into example.

**Comment by PiXeL16** [comment]
Not sure if I understand the screenshot, but the patch looks good. Can you send a `PR`?
Thanks!

**Comment by ghost** [comment]
Done.
