### ISSUE TITLE
is it possible to use it only on Launch Screen ?

### ISSUE THREAD

**Issue by X901** [PiXeL16/RevealingSplashView#25]
Hi ,
It's good library I like it , but I don't like the idea of add it on first view controller because my application won't be on same view controller everytime 
what I mean if the user was on any view controller and then close the app and after that open it again 
he will be on same view controller as which he was
there isn't a 

So only way to be sure the splash animation will display when the app has been open is on launch screen

**Comment by PiXeL16** [comment]
You will have to control that by your self. The library was not designed with that functionality in mind.
