### ISSUE TITLE
Can't fit the screen when use with iPad split view

### ISSUE THREAD

**Issue by xavier-lmk** [PiXeL16/RevealingSplashView#26]
Hi, I find a problem when use split view in iPad. If launch app in split view mode, the splash view size keep the full-screen size. It cannot adjust correctly size.

I found to change following code can work
`super.init(frame: UIScreen.main.bounds)`
to
`super.init(frame: (UIApplication.shared.windows.first!.bounds))`

**Comment by PiXeL16** [comment]
Great! Can you submit a `PR` with your change? ❤️

**Comment by xavier-lmk** [comment]
ok, submitted #27

**Comment by PiXeL16** [comment]
Awesome 🎉 👍
