### ISSUE TITLE
Swift 3.1 support

### ISSUE THREAD

**Issue by saldous** [PiXeL16/RevealingSplashView#28]
With xcode 8.3 and Swift 3.1 there is a build error:

M_PI is deprecated.

**Comment by PiXeL16** [comment]
Would you like to look into this? PR are super welcome! I don't have time to look at it this week.

**Comment by saldous** [comment]
Just replace M_PI with: Double.pi.  Easy fix

**Comment by baschte** [comment]
@PiXeL16 @saldous set a PullRequest with needed changes

**Comment by saldous** [comment]
@PiXeL16 The submitted pull request has a build error

**Comment by PiXeL16** [comment]
@saldous  It should be fixed now. Will be releasing a new version of the Pod today as well.
