### ISSUE TITLE
will RevealingSplashView support carthage in future?

### ISSUE THREAD

**Issue by litt1e-p** [PiXeL16/RevealingSplashView#3]
hi, RevealingSplashView is great! but it seems dont support carthage

**Comment by PiXeL16** [comment]
Hi @litt1e-p , What error are you getting? It theory it should work by only adding the github repo, right?.
Something like `github "PiXeL16/RevealingSplashView"`?

**Comment by litt1e-p** [comment]
yeah. it works by dragging into my project. installation via Carthage will
be a another good choice for those Carthage users. never mind

2016年5月7日星期六，Chris Jimenez notifications@github.com 写道：

**Comment by PiXeL16** [comment]
I mean to add the github Repo in your Carthage file. Like: `github "PiXeL16/RevealingSplashView".` What error do you get if you do that?

**Comment by litt1e-p** [comment]
sorry, I don't know it has supported Carthage. I have included it via
Carthage. thanks!

2016年5月7日星期六，Chris Jimenez notifications@github.com 写道：

**Comment by PiXeL16** [comment]
Ok cool! Glad that it worked.
Closing the issue!
