### ISSUE TITLE
App Crashing In Mobile Device SomeTimes, Here is the Crash Report In Swift 3

### ISSUE THREAD

**Issue by zaidkhan0** [PiXeL16/RevealingSplashView#32]
Incident Identifier: 0534C147-FE98-4A3A-B687-113BC12F03D3
CrashReporter Key:   7734302ba6a56c065a6000407b53c517d64b4428
Hardware Model:      iPhone8,2
Process:             MQ [6321]
Path:                /private/var/containers/Bundle/Application/6E62E705-2A3E-4E37-AB1C-430FD465AC2F/MQ.app/MQ
Identifier:          MQOFFICIAL.MQ
Version:             1 (1.0.0.1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           MQOFFICIAL.MQ [1933]

Date/Time:           2017-06-08 19:03:47.9989 -0500
Launch Time:         2017-06-08 19:03:47.9273 -0500
OS Version:          iPhone OS 10.3.1 (14E304)
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/RevealingSplashView.framework/RevealingSplashView | Referenced from: /var/containers/Bundle/Application/6E62E705-2A3E-4E37-AB1C-430FD465AC2F/MQ.app/MQ | Reason: no suitable image found.  Did find: | /private/var/containers/Bundle/Application/6E62E705-2A3E-4E37-AB1C-430FD465AC2F/MQ.app/Frameworks/RevealingSplashView.framework/RevealingSplashView: mach-o, but wrong architecture | /private/var/containers/Bundle/Application/6E62E705-2A3E-4E37-AB1C-430FD465AC2F/MQ.app/Frameworks/RevealingSplashView.framework/RevealingSplashView: mach-o, but wrong architecture | /private/var/containers/Bundle/Application/6E62E705-2A3E-4E37-AB1C-430FD465AC2F/MQ.app/Frameworks/RevealingSplashView.framework/RevealingSplashView: mach-o, but wrong architecture
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 Crashed:
0   dyld                          	0x000000010023e8bc __abort_with_payload + 8
1   dyld                          	0x000000010023e268 abort_with_payload_wrapper_internal + 100
2   dyld                          	0x000000010023e294 fcntl + 0
3   dyld                          	0x000000010021c3bc dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 0
4   dyld                          	0x000000010021e9c4 dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 4416
5   dyld                          	0x0000000100219044 _dyld_start + 68

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000002   x2: 0x000000016fd2a620   x3: 0x00000000000000a1
    x4: 0x000000016fd2a220   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000b10
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x6120676e6f727720  x11: 0x7463657469686372
   x12: 0x2c6f2d6863616d20  x13: 0x6f72772074756220  x14: 0x696863726120676e  x15: 0x0065727574636574
   x16: 0x0000000000000209  x17: 0x0000000000000010  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fd2a220  x21: 0x00000000000000a1  x22: 0x000000016fd2a620  x23: 0x0000000000000002
   x24: 0x0000000000000006  x25: 0x000000010024d000  x26: 0x000000010024fbc8  x27: 0x000000010024d7ac
   x28: 0x000000010024d000   fp: 0x000000016fd2a1f0   lr: 0x000000010023e268
    sp: 0x000000016fd2a1b0   pc: 0x000000010023e8bc cpsr: 0x00000000

Binary Images:
0x1000d4000 - 0x100113fff MQ arm64  <8ef7633022db3129acca5a64976057ab> /var/containers/Bundle/Application/6E62E705-2A3E-4E37-AB1C-430FD465AC2F/MQ.app/MQ
0x100218000 - 0x10024bfff dyld arm64  <a63e8b89c75a3115b54b1f2f469f676a> /usr/lib/dyld

EOF

**Comment by PiXeL16** [comment]
Looks like is not finding the framework in some architectures, any more information on the type of devices that this is happening?

**Comment by zaidkhan0** [comment]
Yes thats right... I did try to find architecture but not able to find.. and the device I am using is iphone 6s plus ...

**Comment by zaidkhan0** [comment]
If you need any type of help so feel free to contact me...

**Comment by PiXeL16** [comment]
It works for me in 6s and 6s plus. Are you integrating the library with Cocoapods?

**Comment by zaidkhan0** [comment]
Yes its work for me too but it happening sometimes.. and yes I am integrating with the cocoapods
