### ISSUE TITLE
Color icon doesn't work

### ISSUE THREAD

**Issue by lancevalour** [PiXeL16/RevealingSplashView#4]
If I use the color icon instead of the white icon, the splashview will change the icon to white and splash.

Is it a bug or feature? 

Below is the code I use.

``` swift
let revealingSplashView = RevealingSplashView(iconImage: UIImage(named: "color_icon")!, iconInitialSize: CGSizeMake(60, 60),backgroundColor: MaterialColor.grey.lighten5)
```

**Comment by PiXeL16** [comment]
Its definitely not a intented `feature`. I will try to check tonight to see whats up.
Thanks!

**Comment by PiXeL16** [comment]
@lancevalour Just remember that I added a `iconColor` property. If you don't set it it will default to white.
So, for example, you can do:

```
 revealingSplashView.iconColor = UIColor.blueColor()
```

This will change the icon color to blue, the example it will look like this:
<img width="578" alt="screen shot 2016-07-19 at 10 23 06 pm" src="https://cloud.githubusercontent.com/assets/6887660/16974958/4fda38a4-4dff-11e6-8fed-c926783bf9b7.png">

Let me know if it works. Closing for now.
