### ISSUE TITLE
Video Tutorial on YouTube

### ISSUE THREAD

**Issue by rebeloper** [PiXeL16/RevealingSplashView#43]
![maxresdefault](https://user-images.githubusercontent.com/2488011/39059760-1e59046a-44c8-11e8-9f7a-0c73f5b7ae1c.jpg)

Hi,

I like your repository so much that I have created a step by step video tutorial on how to use it. 

Take a look at it here: https://www.youtube.com/watch?v=jtCsh4R8UWo

Let me know what do you think about it and if you wish you can add it to your ReadMe file.
Thank you again for this great repository.

Alex

**Comment by PiXeL16** [comment]
Cool video! Glad you like the control. I will update the Readme with a link to the video as well!
