### ISSUE TITLE
Unable to compile (installed via Cocoapods) after main project has migrated to Swift 4.2

### ISSUE THREAD

**Issue by MattCarr147** [PiXeL16/RevealingSplashView#46]
RevealingSplashView is not currently compatible with Swift 4.2, so once the main project has been migrated it can't be compiled without manually setting the //Swift Language Version// of the RevealingSplashView Target to 'Swift 4'.

Not sure what the preferred way to solve this would be:

- The current podspec could be updated, with the **spec.swift_version** property set to '4.0'
- Wait until Swift 4.2 has been released fully and migrate accordingly.

I think in either case, ultimately setting the **swift_version** in the podspec would be useful to avoid this sort of thing in the future.

The build errors themselves aren't serious and look to have been addressed by #45.

**Comment by PiXeL16** [comment]
Thanks for the recomendations! I'll update when 4.2 its released and add the spec.swift_version accordingly.
