### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by saldous** [PiXeL16/RevealingSplashView#48]
'UIImageRenderingMode' has been renamed to 'UIImage.RenderingMode'
and
'UIViewContentMode' has been renamed to 'UIView.ContentMode'
and
'UIViewAnimationOptions' has been renamed to 'UIView.AnimationOptions'
and
'kCAMediaTimingFunctionEaseInEaseOut' has been renamed to 'CAMediaTimingFunctionName.easeInEaseOut'

**Comment by PiXeL16** [comment]
Will try to work on this over the weekend. It will be great if you have time and want to send a PR with the fix as well 👍

**Comment by weakfl** [comment]
Here you go: #49
