### ISSUE TITLE
Image is not loading at the time of the animation

### ISSUE THREAD

**Issue by CarlosGzz** [PiXeL16/RevealingSplashView#5]
This is my code its setup on the entry viewcontroller, and the launchscreen image has the same size image.
override func viewDidLoad() {
        super.viewDidLoad()

```
    //Initialize a revealing Splash with with the iconImage, the initial size and the background color
    let revealingSplashView = RevealingSplashView(iconImage: UIImage(named:"TanksLogo")!, iconInitialSize: CGSizeMake(100, 100), backgroundColor: UIColor.init(netHex: 0xFDDD26))

    //Adds the revealing splash view as a sub view
    //revealingSplashView.iconImage = UIImage(named:"TanksLogo")!
    self.view.addSubview(revealingSplashView)

    revealingSplashView.duration = 0.9

    revealingSplashView.animationType = SplashAnimationType.PopAndZoomOut

    revealingSplashView.startAnimation(){
           //Stuff
    }
```

**Comment by PiXeL16** [comment]
The code looks fine. Can you try with a different image or a different background?
What do you mean it is not loading? Its just not showing?

**Comment by PiXeL16** [comment]
Closing due to lack of response. Feel free to open it again if you have more issues.

**Comment by AndrewSad** [comment]
hello there, I’m having same issue
my code look like that:

```
let iconImage = UIImage(named: "logo_splash.png")!
let revealingSplashView = RevealingSplashView(iconImage: iconImage,iconInitialSize: CGSizeMake(309, 134), backgroundColor: colorNewNavBarBack())
self.view.addSubview(revealingSplashView)
revealingSplashView.duration = 0.9
revealingSplashView.animationType = SplashAnimationType.Twitter
revealingSplashView.startAnimation(){
}
```

it works all ok except actual image: instead of the image I see blank white rectangle

UPDATE: not an issue in the end; the thing is your default white color for iconColor, icon should be transparent for proper rendering

**Comment by PiXeL16** [comment]
Hi there.
This is probably related to your actual image. The code use `IconImage.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)` to be able to ignore the color information and "paint it" white or any color you set on the property. 
Can you try with this image and let me know if it works?
![twitterlogo](https://cloud.githubusercontent.com/assets/6887660/17526366/2db7c496-5e24-11e6-9c6f-985bea80b3c6.png)
There is actually white logo with a transparent background image here☝️ 
Also, are you sure that your image background is completely transparent?

**Comment by AndrewSad** [comment]
so, my «issue» was that I was using non-transparent icon, so for this thing to work icon for splash screen with colored background MUST be ALWAYS transparent

**Comment by PiXeL16** [comment]
Yes, that was the original idea. But it should be fairly easy to change so `UIImageRenderingMode.AlwaysTemplate` is not enforced. Ill try to fix it later today!

**Comment by AndrewSad** [comment]
ty for quick response

**Comment by PiXeL16** [comment]
Hi @AndrewSad just release Pod `0.0.7` that should fix this issue.
Now the default should be to accept any image (Transparent or non transparent background).
Let me know if it works 👍 

Guessing that you don't need this. But there is a also new property that enable to change the image to a custom color.

```
revealingSplashView.useCustomIconColor = true
revealingSplashView.iconColor = UIColor.redColor()
```

**Comment by AndrewSad** [comment]
working like a charm now, big thanks :)
second feature, custom icon color, is not applicable if icon image is not transparent tho, so in fact that new feature doesn’t support the fix you made in «first»

**Comment by PiXeL16** [comment]
Hi,
Yes, you can't have both im afraid. If you want to change your icon color ir should have a transparent background for it to work.
Glad to know that it worked. Closing for know. 
Let me know if you have any more issues.
Thanks!
