### ISSUE TITLE
Carthage Task failed with exit code 65:

### ISSUE THREAD

**Issue by artuan** [PiXeL16/RevealingSplashView#50]
I cannot install it with Carthage:

*** xcodebuild output can be found in /var/folders/ml/vwq3w1xn44d1j0lfbr77t6cw0000gn/T/carthage-xcodebuild.stHeqG.log
*** Building scheme "RevealingSplashView" in RevealingSplashView.xcworkspace
Build Failed
	Task failed with exit code 65:

Is there a workaround to install it manually?

**Comment by artuan** [comment]
Is there for this issue to be fixed?

**Comment by PiXeL16** [comment]
Hi, It's not something that I currently have time to look into.
If you have ideas, PRs are very welcome.
Thank you

**Comment by marekpridal** [comment]
@PiXeL16 Here is a PR 🙂

**Comment by marekpridal** [comment]
Thanks a lot for submit PR 🙌 are you going to release a new version or should we use master as Carthage origin?

**Comment by PiXeL16** [comment]
0.7.0 should contain the fix now!.

**Comment by PiXeL16** [comment]
@marekpridal As a contributor. You should have commit access to the repo now 👍
