### ISSUE TITLE
Please update to swift 5... I am waiting.

### ISSUE THREAD

**Issue by axceptions** [PiXeL16/RevealingSplashView#54]
Please update to swift 5

**Comment by romeugodoi** [comment]
+1

**Comment by lchamp** [comment]
@PiXeL16 ? PR is ready since a few months...

**Comment by PiXeL16** [comment]
Sorry, Merged now

**Comment by lchamp** [comment]
@PiXeL16 @axceptions can you close this issue as it is resolved?
