### ISSUE TITLE
Keyword for protocol inheritance is deprecated

### ISSUE THREAD

**Issue by lchamp** [PiXeL16/RevealingSplashView#56]
File: SplashAnimatable.swift
Line: 16

Warning:
> Using `class` keyword for protocol inheritance is deprecated; use `AnyObject` instead

Fix:
> Replace `class` with `AnyObject`

Can you fix @PiXeL16 ? Thanks in advance!

**Comment by lchamp** [comment]
👋🏼 @PiXeL16 👋🏼

**Comment by PiXeL16** [comment]
@lchamp Just gave you collaborator access to the repo, as I dont have too much time to maintain anymore. Please take good care of it ;)

**Comment by lchamp** [comment]
Thanks! Solved with new version 0.9.0.
