### ISSUE TITLE
SwiftUI support?

### ISSUE THREAD

**Issue by pradeepb28** [PiXeL16/RevealingSplashView#58]
any plans to support for SwiftUI?

**Comment by PiXeL16** [comment]
I don't have too much time now to add this, but feel free to send a PR

**Comment by ghost** [comment]
It's so easy to implement same UI animation in SwiftUI.
@pradeepb28 implement is by yourself.

**Comment by PiXeL16** [comment]
Not sure if I understand the point of your comment on an issue opened 2 years ago.

**Comment by ghost** [comment]
To help anybody else that find this issue.
