### ISSUE TITLE
Update To Swift 3.0

### ISSUE THREAD

**Issue by the-freshlord** [PiXeL16/RevealingSplashView#7]
Will a Swift 3.0 branch be created?

**Comment by PiXeL16** [comment]
Sure! Working on it tomorow! 🎉

**Comment by moghtaderi** [comment]
+1  Any updates for this?

**Comment by PiXeL16** [comment]
Almost there guys! Had a busy weekend.

**Comment by PiXeL16** [comment]
Swift 3.0 version is Up!. Please update your pods 🎉. Let me know how it goes!
Closing for now.
