### ISSUE TITLE
Icon location

### ISSUE THREAD

**Issue by saren-p** [PiXeL16/RevealingSplashView#8]
Love the splash screen, thank you.

My LaunchScreen.xib has a 80x80 logo image set centered with X/Y constrains. When I run my app, my LaunchScreen is displayed with my logo image centered properly.

However, that being said, the splash screen logo (also set to 80x80) is displayed about 10/15 pixels lower. Is there any way we can add padding to the splash screen logo so as to align both the splash screen logo and the LaunchScreen logo?

This may be because I have navigation items set.

Thanks.

**Comment by PiXeL16** [comment]
Hi @saren-p. I think its definitely because your navigation bar.
You can take a look at #6. There are a couple of good options for you to try there.
Let me know how it goes 👍

**Comment by PiXeL16** [comment]
Duplicated of #6
